CREATE TABLE IF NOT EXISTS subscriber (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    phone_number VARCHAR(11) NOT NULL UNIQUE
);

INSERT INTO subscriber (phone_number)
SELECT '7' || RIGHT('0000000000' || CAST(FLOOR(RAND() * 1E10) AS VARCHAR), 10)
FROM SYSTEM_RANGE(1, 10);
